import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Properties;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author my pc
 */
public class Service_Reminder extends javax.swing.JFrame {

    /**
     * Creates new form Service_Reminder
     */
    public Service_Reminder() {
        initComponents();

    }
    public void time() throws ParseException{
        try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
    Statement st=con.createStatement();
    PreparedStatement pst=null;
    String q="select Renew_date from ser";
    pst=con.prepareStatement(q);
    ResultSet rs=pst.executeQuery();
    SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");      //implementing date format
    while(rs.next()){
        String date=rs.toString();                              //converting object to string
        Date da=s.parse(date);                                  //converting string to date
        Calendar cal=new GregorianCalendar();
        for(int i=15;i<0;i--){                                  //reminder mail will be send to all registered emails 15 days prior of renew date
        cal.add(Calendar.DATE,-i);                              //decrementing 15 days 
        if(date==s.format(cal.getTime())){                      //checking if system date is equal
            
        
    Timer tim=new Timer();
    
    tim.schedule(new TimerTask() {

    @Override
        public void run()  {
            try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
    Statement st=con.createStatement();
    PreparedStatement pst=null;
    String q="select email from members";
    pst=con.prepareStatement(q);
    ResultSet rs=pst.executeQuery();
    while(rs.next()){
    
String to=rs.toString();                                    //emplyoees email
String fromEmail="koroseii19@gmail.com";                    //admins email
String fromPass="phirsepuch";                               //admins gmail password
String sub="Reminder of your due payment---";

Properties proper=new Properties();                         //smtp used for gmail
proper.put("mail.smtp.auth","true");
proper.put("mail.smtp.starttls.enable","true");
proper.put("mail.smtp.host","smtp.gmail.com");
proper.put("mail.smtp.port","587");

Session sess=Session.getDefaultInstance(proper,new javax.mail.Authenticator() {
    protected PasswordAuthentication getPasswordAuthentication(){               //checking password athentication
        return new PasswordAuthentication(fromEmail,fromPass);
    }
});

try{
    MimeMessage mess=new MimeMessage(sess);                                     //Message properties are used for sunding message
    mess.setFrom(new InternetAddress(fromEmail));
    mess.addRecipient(Message.RecipientType.TO,new InternetAddress(to));
    mess.setSubject(sub);
    mess.setText("Dear Client,"+"\n"+"This is a reminder for your due payment of the service that our company has provided to you."+"\n"+"So, kindly deposist your amount in the due time"+"\n"+"Thanking You");
    Transport.send(mess);
    JOptionPane.showMessageDialog(null,"Message Sent");
} catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
          
    }}catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
    }}, da);
    }
        }} }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jlbl5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jlbl1 = new javax.swing.JLabel();
        jlbl4 = new javax.swing.JLabel();
        jlbl6 = new javax.swing.JLabel();
        jlbl2 = new javax.swing.JLabel();
        jblb3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jlbl7 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        deleteall = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nameos = new javax.swing.JTextField();
        servd = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rendat = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        resper = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        vendnam = new javax.swing.JTextField();
        rema = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        tf9 = new javax.swing.JTextField();
        backlogin = new javax.swing.JButton();
        clearsignup = new javax.swing.JButton();
        submitdetails = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jp = new javax.swing.JPasswordField();
        jp1 = new javax.swing.JPasswordField();
        check = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        login = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("new.png")));
        jFrame1.setMinimumSize(new java.awt.Dimension(1366, 750));
        jFrame1.setUndecorated(true);
        jFrame1.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Terminator Two", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SERVICES");
        jFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 30, 320, 50);

        jlbl5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl5.setForeground(new java.awt.Color(255, 255, 255));
        jlbl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbl5.setText("*Mandatory");
        jFrame1.getContentPane().add(jlbl5);
        jlbl5.setBounds(1110, 250, 200, 20);

        jLabel11.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Service start date:-");
        jFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 280, 320, 50);

        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf1FocusLost(evt);
            }
        });
        jFrame1.getContentPane().add(tf1);
        tf1.setBounds(510, 170, 260, 50);

        jLabel12.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Renew date:-");
        jFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 380, 210, 50);

        jLabel13.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Vendor Name:-");
        jFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(810, 300, 210, 50);

        jLabel14.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Module:-");
        jFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(900, 400, 150, 50);

        tf5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf5FocusLost(evt);
            }
        });
        jFrame1.getContentPane().add(tf5);
        tf5.setBounds(1050, 300, 260, 50);

        tf6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf6FocusLost(evt);
            }
        });
        jFrame1.getContentPane().add(tf6);
        tf6.setBounds(1050, 400, 260, 50);

        submit.setBackground(new java.awt.Color(0, 177, 106));
        submit.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUbmit details");
        submit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(submit);
        submit.setBounds(140, 620, 240, 70);

        view.setBackground(new java.awt.Color(34, 167, 240));
        view.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("view report");
        view.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(view);
        view.setBounds(1010, 620, 230, 70);

        jLabel16.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email Id:-");
        jFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(880, 190, 150, 50);

        jTextField2.setEditable(false);
        jTextField2.setEnabled(false);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField2);
        jTextField2.setBounds(1050, 190, 260, 50);

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooser1FocusLost(evt);
            }
        });
        jFrame1.getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(500, 290, 210, 30);

        jDateChooser2.setDateFormatString("dd-MM-yyyy");
        jDateChooser2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateChooser2FocusLost(evt);
            }
        });
        jFrame1.getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(510, 390, 200, 30);

        jLabel22.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Name of the services:-");
        jFrame1.getContentPane().add(jLabel22);
        jLabel22.setBounds(150, 170, 390, 50);

        jlbl1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl1.setForeground(new java.awt.Color(255, 255, 255));
        jlbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbl1.setText("*Mandatory");
        jFrame1.getContentPane().add(jlbl1);
        jlbl1.setBounds(410, 230, 360, 20);

        jlbl4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl4.setForeground(new java.awt.Color(255, 255, 255));
        jlbl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbl4.setText("*Mandatory");
        jFrame1.getContentPane().add(jlbl4);
        jlbl4.setBounds(470, 550, 300, 20);

        jlbl6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl6.setForeground(new java.awt.Color(255, 255, 255));
        jlbl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbl6.setText("*Mandatory");
        jFrame1.getContentPane().add(jlbl6);
        jlbl6.setBounds(990, 360, 320, 20);

        jlbl2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl2.setForeground(new java.awt.Color(255, 255, 255));
        jlbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbl2.setText("*Mandatory");
        jFrame1.getContentPane().add(jlbl2);
        jlbl2.setBounds(500, 330, 200, 20);

        jblb3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jblb3.setForeground(new java.awt.Color(255, 255, 255));
        jblb3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblb3.setText("*Mandatory");
        jFrame1.getContentPane().add(jblb3);
        jblb3.setBounds(510, 430, 200, 20);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        logout.setBackground(new java.awt.Color(30, 130, 76));
        logout.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("logout");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Responsible person:-");

        tf4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf4FocusLost(evt);
            }
        });

        jlbl7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlbl7.setForeground(new java.awt.Color(255, 255, 255));
        jlbl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbl7.setText("*Mandatory");

        jLabel7.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("remarks:-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(549, 549, 549)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(jlbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        jFrame1.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 90, 1370, 680);

        jPanel4.setBackground(new java.awt.Color(248, 148, 6));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("-");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ll.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1024, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFrame1.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1370, 90);

        jFrame2.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("new.png")));
        jFrame2.setMinimumSize(new java.awt.Dimension(1366, 755));
        jFrame2.setUndecorated(true);
        jFrame2.getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><body><font face=\"Terminator Two\">SLno.</font></body></html>", "<html><body><font face=\"Terminator Two\">Name of the service</font></body></html> ", "<html><body><font face=\"Terminator Two\">Service start date</font></body></html>", "<html><body><font face=\"Terminator Two\">Renew date</font></body></html>", "<html><body><font face=\"Terminator Two\">Responsible person</font></body></html>", "<html><body><font face=\"Terminator Two\">Email ID</font></body></html>", "<html><body><font face=\"Terminator Two\">Vendor name</font></body></html>", "<html><body><font face=\"Terminator Two\">Module</font></body></html>", "<html><body><font face=\"Terminator Two\">Remarks</font></body></html>"
            }
        ));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jFrame2.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1370, 320);

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));

        jButton6.setBackground(new java.awt.Color(207, 0, 15));
        jButton6.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Exit");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        deleteall.setBackground(new java.awt.Color(192, 57, 43));
        deleteall.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        deleteall.setForeground(new java.awt.Color(255, 255, 255));
        deleteall.setText("delete all");
        deleteall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteallActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Name of service:-");

        servd.setDateFormatString("dd-MM-yyyy");

        jLabel15.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Service date:-");

        jLabel21.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Renew date:-");

        rendat.setDateFormatString("dd-MM-yyyy");

        jLabel17.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Vendors name:-");

        jLabel20.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Email id:-");

        jLabel24.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Responsible person:-");

        jLabel23.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Module:-");

        jLabel19.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Remarks:-");

        update.setBackground(new java.awt.Color(34, 167, 240));
        update.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("edit");
        update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(211, 84, 0));
        clear.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(30, 130, 76));
        back.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(deleteall)
                .addGap(105, 105, 105)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(nameos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rendat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(servd, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGap(10, 10, 10)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendnam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resper, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rema, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resper, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(mod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(servd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vendnam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(rendat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteall, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jFrame2.getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1370, 750);

        jFrame3.setTitle("SIGN UP");
        jFrame3.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("new.png")));
        jFrame3.setMinimumSize(new java.awt.Dimension(1366, 755));
        jFrame3.setUndecorated(true);
        jFrame3.setSize(new java.awt.Dimension(0, 0));
        jFrame3.getContentPane().setLayout(null);

        tf9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf9FocusLost(evt);
            }
        });
        jFrame3.getContentPane().add(tf9);
        tf9.setBounds(350, 440, 270, 60);

        backlogin.setBackground(new java.awt.Color(34, 167, 240));
        backlogin.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        backlogin.setForeground(new java.awt.Color(255, 255, 255));
        backlogin.setText("BACK TO LOGIN");
        backlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backloginActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(backlogin);
        backlogin.setBounds(270, 620, 220, 70);

        clearsignup.setBackground(new java.awt.Color(192, 57, 43));
        clearsignup.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        clearsignup.setForeground(new java.awt.Color(255, 255, 255));
        clearsignup.setText("CLEAR DATA");
        clearsignup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearsignupActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(clearsignup);
        clearsignup.setBounds(940, 620, 200, 70);

        submitdetails.setBackground(new java.awt.Color(30, 130, 76));
        submitdetails.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        submitdetails.setForeground(new java.awt.Color(255, 255, 255));
        submitdetails.setText("SUBMIT DETAILS");
        submitdetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitdetailsActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(submitdetails);
        submitdetails.setBounds(587, 620, 230, 70);

        jLabel26.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("confirm PASSWORD:-");
        jFrame3.getContentPane().add(jLabel26);
        jLabel26.setBounds(640, 430, 320, 60);
        jFrame3.getContentPane().add(tf3);
        tf3.setBounds(350, 300, 270, 60);

        jLabel28.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Location:-");
        jFrame3.getContentPane().add(jLabel28);
        jLabel28.setBounds(160, 300, 190, 50);

        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });
        jFrame3.getContentPane().add(tf2);
        tf2.setBounds(350, 170, 270, 60);

        jLabel29.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("PHONE NUMBER:-");
        jFrame3.getContentPane().add(jLabel29);
        jLabel29.setBounds(700, 170, 260, 50);

        tf10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf10FocusLost(evt);
            }
        });
        jFrame3.getContentPane().add(tf10);
        tf10.setBounds(970, 170, 310, 60);

        jLabel31.setFont(new java.awt.Font("Terminator Two", 1, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("ENTER YOUR DETAILS");
        jFrame3.getContentPane().add(jLabel31);
        jLabel31.setBounds(310, 10, 660, 70);

        jPanel6.setBackground(new java.awt.Color(248, 148, 6));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("-");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("X");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ll.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1024, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jFrame3.getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1370, 80);

        jPanel7.setBackground(new java.awt.Color(44, 62, 80));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("*Mandatory");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("*Mandatory");

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("*Mandatory");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("*Mandatory");

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("*Mandatory");

        jLabel25.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Email:-");

        jLabel30.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("NAME:-");

        jLabel27.setFont(new java.awt.Font("Terminator Two", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("password:-");

        jp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpFocusLost(evt);
            }
        });

        jp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jp1FocusLost(evt);
            }
        });
        jp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jp1KeyReleased(evt);
            }
        });

        check.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout checkLayout = new javax.swing.GroupLayout(check);
        check.setLayout(checkLayout);
        checkLayout.setHorizontalGroup(
            checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        checkLayout.setVerticalGroup(
            checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jp1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel35)
                        .addGap(230, 230, 230))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jFrame3.getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 70, 1370, 680);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("new.png")));
        setMinimumSize(new java.awt.Dimension(1366, 755));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Terminator Two", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(510, 30, 390, 38);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1260, 0, 49, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1311, 0, 45, 60);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ll.png"))); // NOI18N
        jPanel1.add(jLabel39);
        jLabel39.setBounds(0, 0, 180, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1360, 70);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("PASSWORD:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("EMAIL:");

        jTextField1.setBackground(new java.awt.Color(108, 122, 137));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jPasswordField1.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));

        signup.setBackground(new java.awt.Color(192, 57, 43));
        signup.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(34, 167, 240));
        login.setFont(new java.awt.Font("Terminator Two", 1, 21)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addGap(446, 446, 446))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(316, 316, 316)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(885, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(804, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(291, 291, 291)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addGap(106, 106, 106)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(457, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(518, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 1360, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
System.exit(0);

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusLost
        String name_of_service=tf1.getText();
        if(name_of_service.equals("")){
           jlbl1.setForeground(Color.red);
           jlbl1.setText("The Name Of The Service field is mandatory");
        }else{
            jlbl1.setForeground(Color.white);
            jlbl1.setText("*Mandatory");
        }
    }//GEN-LAST:event_tf1FocusLost

    private void tf5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf5FocusLost
        String vendor_name=tf5.getText();
        if(vendor_name.equals("")){
           jlbl6.setForeground(Color.red);
           jlbl6.setText("The Vendor Name field is mandatory");
        }else{
            jlbl6.setForeground(Color.white);
            jlbl6.setText("*Mandatory");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_tf5FocusLost

    private void tf6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf6FocusLost
        String Module=tf6.getText();
        if(Module.equals("")){
            jlbl7.setForeground(Color.red);
           jlbl7.setText("The Module field is mandatory");
        }else{
            jlbl7.setForeground(Color.white);
            jlbl7.setText("*Mandatory");
        }
    }//GEN-LAST:event_tf6FocusLost

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String name_of_service=tf1.getText();                           //getting inputs from user
        String responsible_person=tf4.getText();
        String email=jTextField2.getText();
        String vendor_name=tf5.getText();
        String Module=tf6.getText();
        String Remark=tf7.getText();
        SimpleDateFormat sd=new SimpleDateFormat("dd-MM-yyyy");
        String start_date=sd.format(jDateChooser1.getDate());
        String renew_date=sd.format(jDateChooser2.getDate());
         if(name_of_service.equals(" ") && responsible_person.equals(" ") && email.equals(" ") && vendor_name.equals(" ") && Module.equals(" ") && Remark.equals(" ") && start_date.equals(" ") && renew_date.equals(" ")){
                JOptionPane.showMessageDialog(this,"All fields are mandatory","Error",JOptionPane.ERROR_MESSAGE);           //checking if all fields are filled
            }else {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
            Statement st=con.createStatement();
            PreparedStatement pst=null;
            String q="insert into ser (Name_of_service,Service_start_date,Renew_date,Responsible_person,Email_Id,Vendor_name,Module,Remark) values(?,?,?,?,?,?,?,?)";
            pst=con.prepareStatement(q);
            pst.setString(1, name_of_service);              //inserting values to database
            pst.setString(2, start_date);
            pst.setString(3, renew_date);
            pst.setString(4, responsible_person);
            pst.setString(5, email);
            pst.setString(6, vendor_name);
            pst.setString(7, Module);
            pst.setString(8, Remark);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added Successfully","Good",JOptionPane.INFORMATION_MESSAGE);
           
            tf1.setText("");                                    //clearing all data fields
            jDateChooser1.setCalendar(null);
            jDateChooser2.setCalendar(null);
            tf4.setText("");
            tf5.setText("");
            tf6.setText("");
            tf7.setText("");
            jTextField1.setText("");
      con.close();
       
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        jFrame2.setVisible(true);
        jFrame1.setVisible(false);
        
        TableColumnModel col=jTable1.getColumnModel();
        col.getColumn(0).setPreferredWidth(50);
        col.getColumn(1).setPreferredWidth(180);
        col.getColumn(2).setPreferredWidth(100);
        col.getColumn(3).setPreferredWidth(80);
        col.getColumn(4).setPreferredWidth(150);
        col.getColumn(5).setPreferredWidth(80);
        col.getColumn(6).setPreferredWidth(80);
        col.getColumn(7).setPreferredWidth(50);
        col.getColumn(8).setPreferredWidth(50);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
            String q="select * from ser";
            PreparedStatement pst=con.prepareStatement(q);
            ResultSet rs=pst.executeQuery();
            DefaultTableModel ts=(DefaultTableModel)jTable1.getModel();
            ts.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("Slno"),rs.getString("Name_of_service"),rs.getString("Service_start_date"),rs.getString("Renew_date"),rs.getString("Responsible_person")
                    ,rs.getString("Email_Id"),rs.getString("Vendor_name"),rs.getString("Module"),rs.getString("Remark")};
                ts.addRow(o);
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        String email=jTextField1.getText();
        if(email.equals("")){
             jlbl5.setForeground(Color.red);
           jlbl5.setText("The Email field is mandatory");
        }else{
            jlbl5.setForeground(Color.white); 
            jlbl5.setText("*Mandatory");
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jDateChooser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser1FocusLost
        SimpleDateFormat sd=new SimpleDateFormat("dd-MM-yyyy");
        String start_date=sd.format(jDateChooser1.getDate());
        if(start_date.equals("")){
             jlbl2.setForeground(Color.red);
           jlbl2.setText("The Service Date field is mandatory");
        }else{
            jlbl2.setForeground(Color.white); 
            jlbl2.setText("*Mandatory");
        }
    }//GEN-LAST:event_jDateChooser1FocusLost

    private void jDateChooser2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser2FocusLost
        SimpleDateFormat sd=new SimpleDateFormat("dd-MM-yyyy");
        String renew_date=sd.format(jDateChooser2.getDate());
        if(renew_date.equals("")){
             jblb3.setForeground(Color.red);
           jblb3.setText("The Renew Date field is mandatory");
        }else{
            jblb3.setForeground(Color.white); 
            jblb3.setText("*Mandatory");
        }
    }//GEN-LAST:event_jDateChooser2FocusLost

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
     String email=tf9.getText();                //getting data from user
     jTextField2.setText(email);
     String a=jTextField1.getText();
     String b=String.valueOf(jPasswordField1.getPassword());
     try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
    Statement st=con.createStatement();
    PreparedStatement pst=null;
    String q="select * from members where email=? and password=?";
    pst=con.prepareStatement(q);
    pst.setString(1, a);
    pst.setString(2, b);
    //pst.executeUpdate();
    ResultSet rs=pst.executeQuery();
    if(rs.next()){                              //checking if the email and password are correct or not
        jFrame1.setVisible(true);
        this.setVisible(false);
        jTextField1.setText("");
        jPasswordField1.setText("");
    }
    else{
         JOptionPane.showMessageDialog(null, "Email and Password doesn't Matched","Error",JOptionPane.ERROR_MESSAGE);
         jTextField1.setText("");
         jPasswordField1.setText("");
    }
    PreparedStatement pst1=null;
    String mail=jTextField1.getText();                                  //getting the corressponding email and print in next frame's text field
    String qu="select email from members where email=?"+mail;
    pst1=con.prepareStatement(qu);
    ResultSet rs1=pst.executeQuery();
    if(rs1.next()){                                         
        jTextField2.setText(rs1.getString("email"));
    }
    con.close();
} catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_loginActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
jFrame1.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int select=jTable1.getSelectedRow();                                //getting the index number of selected row
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            nameos.setText(model.getValueAt(select, 1).toString());              //printing all the data of table in corressponding data fields
            Date date=new SimpleDateFormat("dd-MM-yyyy").parse((String)model.getValueAt(select, 2));
            servd.setDate(date);
            Date date1=new SimpleDateFormat("dd-MM-yyyy").parse((String)model.getValueAt(select, 3));
            rendat.setDate(date1);
            resper.setText(model.getValueAt(select, 4).toString());
            email.setText(model.getValueAt(select,5).toString());
            vendnam.setText(model.getValueAt(select, 6).toString());
            mod.setText(model.getValueAt(select, 7).toString());
            rema.setText(model.getValueAt(select, 8).toString());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        jFrame1.setVisible(true);
        jFrame2.setVisible(false);
        nameos.setText("");
        resper.setText("");
        servd.setCalendar(null);
        rendat.setCalendar(null);
        resper.setText("");
        mod.setText("");
        rema.setText("");
        vendnam.setText("");
        email.setText("");
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");            //selecting database
            int row=jTable1.getSelectedRow();                                                                       //getting the index number of selected row
            String value=(jTable1.getModel().getValueAt(row,0).toString());                                         //selecting the row that is to be editing
            String q="update ser set Name_of_service=?,Service_start_date=?,Renew_date=?,Responsible_person=?,Email_Id=?,Vendor_name=?,Module=?,Remark=? where Slno="+value;
            PreparedStatement pst=con.prepareStatement(q);
            String em=email.getText();
            String expression = "[A-Za-z0-9_.-]+@+[A-Za-z]+\\.+[A-Za-z]{2,4}+$";
           if(!(Pattern.matches(expression, em))){
            JOptionPane.showMessageDialog(this,"Please enter a valid email address ","Error",JOptionPane.ERROR_MESSAGE);
            }else{
            pst.setString(1, nameos.getText());
            SimpleDateFormat sd=new SimpleDateFormat("dd-MM-yyyy");
            String start_date=sd.format(servd.getDate());
            String renew_date=sd.format(rendat.getDate());
            pst.setString(2, start_date);
            pst.setString(3, renew_date);
            pst.setString(4, resper.getText());
            pst.setString(5, email.getText());
            pst.setString(6, vendnam.getText());
            pst.setString(7, mod.getText());
            pst.setString(8, rema.getText());
            pst.executeUpdate();
            String qu="select * from ser";                                      //viewing the table 
            PreparedStatement pst1=con.prepareStatement(qu);
            ResultSet rs=pst1.executeQuery();
            DefaultTableModel ts=(DefaultTableModel)jTable1.getModel();
            ts.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("Slno"),rs.getString("Name_of_service"),rs.getString("Service_start_date"),rs.getString("Renew_date"),rs.getString("Responsible_person")
                    ,rs.getString("Email_Id"),rs.getString("Vendor_name"),rs.getString("Module"),rs.getString("Remark")};
                ts.addRow(o);
            }
            int row1=jTable1.getRowCount();              //modifying the size of row cells
for(int i=0;i<row1;i++){
    jTable1.setRowHeight(i,80);
}
            JOptionPane.showMessageDialog(this,"Updated Successfully","Good",JOptionPane.INFORMATION_MESSAGE);
                    
        
            nameos.setText("");
            servd.setCalendar(null);
            rendat.setCalendar(null);
            resper.setText("");
            email.setText("");
            vendnam.setText("");
            mod.setText("");
            rema.setText("");
            con.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Select the row that need to be edited","Error",JOptionPane.ERROR_MESSAGE);
        }
           
        
           
           
    
           
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
            Statement st=con.createStatement();
            int row=jTable1.getSelectedRow();
            String value=(jTable1.getModel().getValueAt(row,0).toString());     //getting the value of selected row
            String q="Delete from ser where Slno="+value;                       //changing the value of Slno    
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Sucessfully Deleted The Row");
            String del="alter table ser drop Slno";
            st.executeUpdate(del);
            String ins="alter table ser add Slno int(2) Not Null auto_increment primary key";
            st.executeUpdate(ins);
            String first="alter table ser modify column Slno int(2) auto_increment first";
            st.executeUpdate(first);
            String qu="select * from ser";
            PreparedStatement pst1=con.prepareStatement(qu);
            ResultSet rs=pst1.executeQuery();
            DefaultTableModel ts=(DefaultTableModel)jTable1.getModel();
            ts.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("Slno"),rs.getString("Name_of_service"),rs.getString("Service_start_date"),rs.getString("Renew_date"),rs.getString("Responsible_person")
                    ,rs.getString("Email_Id"),rs.getString("Vendor_name"),rs.getString("Module"),rs.getString("Remark")};
                ts.addRow(o);
            }
            int row1=jTable1.getRowCount();              //modifying the size of row cells
for(int i=0;i<row1;i++){
    jTable1.setRowHeight(i,80);
}
        
            nameos.setText("");
            servd.setCalendar(null);
            rendat.setCalendar(null);
            resper.setText("");
            email.setText("");
            vendnam.setText("");
            mod.setText("");
            rema.setText("");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }//GEN-LAST:event_clearActionPerformed

    private void deleteallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteallActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
            Statement st=con.createStatement();
            String sql="Truncate ser";
            st.executeUpdate(sql);
            sql="Delete from ser";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
            String del="alter table ser drop Slno";
            st.executeUpdate(del);
            String ins="alter table ser add Slno int(2) Not Null auto_increment primary key";
            st.executeUpdate(ins);
            String first="alter table ser modify column Slno int(2) auto_increment first";
            st.executeUpdate(first);
            String qu="select * from ser";
            PreparedStatement pst1=con.prepareStatement(qu);
            ResultSet rs=pst1.executeQuery();
            DefaultTableModel ts=(DefaultTableModel)jTable1.getModel();
            ts.setRowCount(0);
            while(rs.next()){
                Object o[]={rs.getInt("Slno"),rs.getString("Name_of_service"),rs.getString("Service_start_date"),rs.getString("Renew_date"),rs.getString("Responsible_person")
                    ,rs.getString("Email_Id"),rs.getString("Vendor_name"),rs.getString("Module"),rs.getString("Remark")};
                ts.addRow(o);
            }
            //Sting query="alter table auto_increment=1";

            con.close();
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }//GEN-LAST:event_deleteallActionPerformed

    private void backloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backloginActionPerformed
       this.setVisible(true);          //making login page frame visible
            jFrame3.setVisible(false);      //making sign up page invisible
        check.setBackground(Color.decode("#2C3E50"));           //setting the colour of the panel in default colour
       
    }//GEN-LAST:event_backloginActionPerformed

    private void clearsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearsignupActionPerformed
        tf2.setText("");        //clearing all data from fields
        tf10.setText("");
        tf3.setText("");
        jp1.setText("");
        tf9.setText("");
        jp.setText("");
        check.setBackground(Color.decode("#2C3E50"));
    }//GEN-LAST:event_clearsignupActionPerformed

    private void submitdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitdetailsActionPerformed

        String usern1=tf9.getText();
        String expression = "[A-Za-z0-9_.-]+@+[A-Za-z]+\\.+[A-Za-z]{2,4}+$";                       //assigning the correct email format
           if(!(Pattern.matches(expression, usern1))){                                          //checking the format
            JOptionPane.showMessageDialog(this,"Please enter a valid email address ","Error",JOptionPane.ERROR_MESSAGE);
        }
        else {
        try{
            String nam=tf2.getText();
        String pnum=tf10.getText();
        String add=tf3.getText();
        String usern=tf9.getText();
        String cpass=String.valueOf(jp1.getPassword());
        String pass=String.valueOf(jp.getPassword());
        if(nam.equals(" ") && pnum.equals(" ") && add.equals(" ") && usern.equals(" ") && cpass.equals(" ")&& pass.equals(" ")){
            JOptionPane.showMessageDialog(this,"All fields are manadtory","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        if(cpass.equals(pass)){
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/service","root","");
            Statement st=con.createStatement();
            PreparedStatement pst=null;
            String q="insert into members(name,phone_number,address,email,password) values(?,?,?,?,?)";      //inserting data in members table
            pst=con.prepareStatement(q);
            pst.setString(1, nam);              //setting data for each row
            pst.setString(2, pnum);
            pst.setString(3, add);
            pst.setString(4, usern);
            pst.setString(5, pass);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added Successfully","Good",JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Back To The Login Page","Good",JOptionPane.INFORMATION_MESSAGE);
            tf2.setText("");        //clearing all data from fields
            tf10.setText("");
            tf3.setText("");
            jp1.setText("");
            tf9.setText("");
            jp.setText("");
            check.setBackground(Color.decode("#2C3E50"));
            this.setVisible(true);          //making login page frame visible
            jFrame3.setVisible(false);      //making sign up page invisible
            con.close();
        }else
            JOptionPane.showMessageDialog(this,"Password doesn't match","Error",JOptionPane.ERROR_MESSAGE);
        }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_submitdetailsActionPerformed

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
System.exit(0);             //closing the application
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
jFrame3.setState(JFrame.ICONIFIED);             //minimize the frame
    }//GEN-LAST:event_jLabel32MouseClicked

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
this.setVisible(false);
jFrame3.setVisible(true);
jTextField1.setText("");
jPasswordField1.setText("");
    }//GEN-LAST:event_signupActionPerformed

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
 String nam=tf2.getText();
    if(nam.equals("")){
        jLabel34.setForeground(Color.red);
        jLabel34.setText("The Name Field is manadtory");
    }else{
        jLabel34.setForeground(Color.white);
            jLabel34.setText("*Mandatory");
        }
    }//GEN-LAST:event_tf2FocusLost

    private void tf9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf9FocusLost
      String mid=tf9.getText();
      if(mid.equals("")){
       jLabel35.setForeground(Color.red);
        jLabel35.setText("The Name Of The Service Field is manadtory");
      }else{
          jLabel35.setForeground(Color.white);
            jLabel35.setText("*Mandatory");
        }
    }//GEN-LAST:event_tf9FocusLost

    private void tf10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf10FocusLost
    String pnum=tf10.getText();
    if(pnum.equals("")){
        jLabel36.setForeground(Color.red);
        jLabel36.setText("The Phone Number Field is manadtory");
    }else{
        jLabel36.setForeground(Color.white);
            jLabel36.setText("*Mandatory");
        }
    }//GEN-LAST:event_tf10FocusLost

    private void jpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpFocusLost
     String pass=String.valueOf(jp.getPassword());
     if(pass.equals("")){
        jLabel37.setForeground(Color.red);
        jLabel37.setText("The Password Field is manadtory");
     }else{
         jLabel37.setForeground(Color.white);
            jLabel37.setText("*Mandatory");
        }
    }//GEN-LAST:event_jpFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
this.setVisible(true);
jFrame1.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void jp1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jp1FocusLost
String pass=String.valueOf(jp1.getPassword());
     if(pass.equals("")){
       jLabel38.setForeground(Color.red);
        jLabel38.setText("The Confirm Password Field is manadtory");
     }else{
         jLabel38.setForeground(Color.white);
            jLabel38.setText("*Mandatory");
        }
    }//GEN-LAST:event_jp1FocusLost

    private void jp1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp1KeyReleased
String cpass=String.valueOf(jp1.getPassword());             //checking the password and confirm password are same
        String pass=String.valueOf(jp.getPassword());
        if(cpass.equals(pass)){
            check.setBackground(Color.green);
        } else
            check.setBackground(Color.red);
    }//GEN-LAST:event_jp1KeyReleased

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
int row=jTable1.getRowCount();              //modifying the size of row cells
for(int i=0;i<row;i++){
    jTable1.setRowHeight(i,80);
}
    }//GEN-LAST:event_viewMouseClicked

    private void tf4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf4FocusLost
String a=tf4.getText();
if(a.equals("")){
     jlbl4.setForeground(Color.red);
           jlbl4.setText("Responsible person field is mandatory");
}
else{
    jlbl4.setForeground(Color.white);
            jlbl4.setText("*Mandatory");
        }
    }//GEN-LAST:event_tf4FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException{
       Service_Reminder a=new Service_Reminder();
        a.time();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service_Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service_Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service_Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service_Reminder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service_Reminder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton backlogin;
    private javax.swing.JPanel check;
    private javax.swing.JButton clear;
    private javax.swing.JButton clearsignup;
    private javax.swing.JButton deleteall;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jblb3;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl2;
    private javax.swing.JLabel jlbl4;
    private javax.swing.JLabel jlbl5;
    private javax.swing.JLabel jlbl6;
    private javax.swing.JLabel jlbl7;
    private javax.swing.JPasswordField jp;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mod;
    private javax.swing.JTextField nameos;
    private javax.swing.JTextField rema;
    private com.toedter.calendar.JDateChooser rendat;
    private javax.swing.JTextField resper;
    private com.toedter.calendar.JDateChooser servd;
    private javax.swing.JButton signup;
    private javax.swing.JButton submit;
    private javax.swing.JButton submitdetails;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf9;
    private javax.swing.JButton update;
    private javax.swing.JTextField vendnam;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("new.png")));
    }
}
